id: P006937
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2508
  title: ཤམྦྷ་ལའི་གོ་རིམ་
  author: ''
  volumes:
    26c0672c9bfe4094a9a20286ad61e226:
      image_group_id: I1CZ2510
      title: ''
      volume_number: 1
      total_pages: 172
ebook_metadata:
  title: ཤམྦྷ་ལའི་གོ་རིམ་
  author: ''
  sku: P006937
  cover: cover.jpg
  layers:
  - pagination
