id: P006937
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:31:45.069691
source_metadata:
  id: bdr:W1CZ2508
  title: ཤམྦྷ་ལའི་གོ་རིམ་
  author: ''
  volumes:
    d25be2f1204a4940956224541848f967:
      image_group_id: I1CZ2510
      title: Volume 1 of shamb+ha la'i go rim
      volume_number: 1
      total_pages: 172
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
